language: node_js
notifications:
  email:
  - yiminghe@gmail.com
node_js:
- 0.1
before_script:
- npm install gulp -g
- gulp server &
- npm install bower -g
- bower install
- phantomjs --version
- npm install mocha-phantomjs -g
script:
- npm test
- mocha-phantomjs http://localhost:8002/tests/runner.html
- mocha-phantomjs http://localhost:8002/tests/runner.html?build
- mocha-phantomjs -R node_modules/node-jscover/lib/reporters/mocha/console http://localhost:8002/tests/runner.html?coverage